##Pair Pandas

##El objetivo de la clase de hoy será crear unos cuántos DataFrames y Series a través de los siguientes ejercicios:

In [4]:
import pandas as pd
import numpy as np
import random


1. ¿Qué diferencia hay entre una Serie y un DataFrame?

La serie es unidimensional y el Dataframe es bidimensional.

2. Momento de trabajar con Series. Contesta a las siguientes preguntas:

Crea dos listas:

Una que se llame "valores" que tenga 7 números aleatorios.

Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [10]:
numeros = [random.randint(1, 10) for _ in range(7)]

indices =["Lunes","Martes","Miercoles","Jueves","Viernes","Sabado","Domingo"]

print(numeros)
print(indices)

[8, 6, 8, 2, 2, 4, 7]
['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']


2.a) A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [11]:
serie_valores = pd.Series(numeros, index=indices)
serie_valores

Lunes        8
Martes       6
Miercoles    8
Jueves       2
Viernes      2
Sabado       4
Domingo      7
dtype: int64

2.b) A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí (https://www.programiz.com/python-programming/methods/built-in/zip)

In [20]:
diccionario = zip(indices,numeros)

dicc_zip=dict(diccionario)

2.c) Crea una Serie con el diccionario creado en el punto anterior.

In [21]:
serie_dict = pd.Series(dicc_zip)

print(serie_dict)

Lunes        8
Martes       6
Miercoles    8
Jueves       2
Viernes      2
Sabado       4
Domingo      7
dtype: int64


2.d) ¿Qué forma tiene esta última Serie?

In [23]:
serie_dict.shape

(7,)

2.e) ¿Qué tipo de datos tiene?

In [24]:
serie_dict.dtype

dtype('int64')

2.f) ¿Qué tamaño tiene?

In [25]:
serie_dict.size

7

2.f) ¿Cuáles son los índices de la Serie?

In [26]:
serie_dict.index

Index(['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado',
       'Domingo'],
      dtype='object')

2.g) ¿Y los values?

In [27]:
serie_dict.values

array([8, 6, 8, 2, 2, 4, 7], dtype=int64)

2.h) Extrae el valor para el índice "lunes"

In [28]:
serie_dict[0]

C:\Users\spine\AppData\Local\Temp\ipykernel_20500\72279151.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  serie_dict[0]


8

2.i) Extrae el valor para el índice "lunes", "martes" y "miércoles".

In [30]:
serie_dict[:3]

Lunes        8
Martes       6
Miercoles    8
dtype: int64

2.j) Extrae el valor para el índice "lunes" y "domingo".

In [38]:
serie_dict[[0,-1]]

C:\Users\spine\AppData\Local\Temp\ipykernel_20500\1433378165.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  serie_dict[[0,-1]]


Lunes      8
Domingo    7
dtype: int64

3. Es el turno de los DataFrames

3.a) Crea un array de dos dimensiones con 4 filas y 3 columnas.

In [40]:
array2d = np.random.randint(0,100,(4,3))

print(array2d)

[[20 18 58]
 [64 97 15]
 [77 27 37]
 [74 21 60]]


3.b) Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [46]:
lista_paises = ["España","Francia","Italia"]

lista_df =[]

for lista in array2d:
    zip_listas = zip(lista_paises,lista)
    lista_df.append(dict(zip_listas))
    
print(lista_df)

[{'España': 20, 'Francia': 18, 'Italia': 58}, {'España': 64, 'Francia': 97, 'Italia': 15}, {'España': 77, 'Francia': 27, 'Italia': 37}, {'España': 74, 'Francia': 21, 'Italia': 60}]


In [48]:
df_array2d = pd.DataFrame(lista_df)
print(df_array2d)

   España  Francia  Italia
0      20       18      58
1      64       97      15
2      77       27      37
3      74       21      60


3.c) Descarga el archivo "medallas" y carga el DataFrame.

In [57]:
url = "https://raw.githubusercontent.com/spinelf/PairProgramming_Modulo03/main/medallas.csv"
df_medallas = pd.read_csv(url,index_col=0)
print(df_medallas)

3.d) Usando el loc extrae todas las columnas de la fila de Tailandia.

In [56]:

fila_tailandia = df_medallas.loc["Tailandia",:]

KeyError: 'Tailandia'

3.e) Usando el loc extrae todas las columnas de China e Irán.

3.f) Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

3.g) Usando el iloc extrae la información de la India. Devolved todas las columnas.

3.h) Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

3.i) Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

3.j) Contesta a las siguientes preguntas:

¿Qué país consiguió más de 200 medallas de oro?

¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

3.k) Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.